#### 1	– Crie um modelo de classificação de imagens, a partir da importação da base de dados do Sci-kit Learn. Este modelo deve ter as seguintes características:
- 1.1	Utilize a base de dados Mnist Dataset;
- 1.2	Divida a base de treinamento e teste em 80/20;
- 1.3	Utilize a técnica de Cross Validation (K-fold = 5);
- 1.4	Utilize a técnica de Random Search ou Grid Search para escolha dos melhores parâmetros
- 1.5	Faça a impressão da matriz de confusão para o modelo


Obs: Fique a vontade para usar outras bibliotecas


**3)** A base de dados está pronta, então vamos utilizar agora o algoritmo SVM para treinar o modelo. Para isso, observe o código a seguir e faça as devidas modificações. Em seguida observe a acurácia deste modelo.

In [ ]:
from sklearn.metrics import accuracy_score 
from sklearn.svm import SVC
import sklearn.metrics as metrics
import numpy as np

#Criando um modelo SVM variando os parâmetros C e gamma
model=SVC(C=0.99, gamma=0.0000001)

#Treinando o modelo. Use aqui suas observações de treino e os targets de treino
model.fit(Xtreino, Ytreino)

#Fazendo predições. Use aqui sua base de teste
result = model.predict(Xteste)

#mostrando os resultados preditos pelo modelo 
print('Resultado:')
print(result)

print('Resultado Esperado:')
#Os resultados esperados são os targets de teste, mostre-os a seguir
print(Yteste)


#agora vamos calcular a acurária do modelo usando a base de testes
print("Acurácia:", metrics.accuracy_score(result,Yteste))

In [ ]:
result = model.predict(Xval)

#mostrando os resultados preditos pelo modelo 
print('Resultado:')
print(result)

print('Resultado Esperado:')
#Os resultados esperados são os targets de teste, mostre-os a seguir
print(Yval)


#agora vamos calcular a acurária do modelo usando a base de testes
print("Acurácia:", metrics.accuracy_score(result,Yval))

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split, KFold
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

import numpy as np

In [2]:
# Carrega a base de dados Mnist Dataset do Sci-kit Learn
digits = datasets.load_digits()

# Define as variáveis X e y
X = digits.data
y = digits.target

In [3]:
# Divide a base de treinamento e teste em 80/20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define os parâmetros a serem testados
n_estimators = [int(x) for x in np.linspace(start = 50, stop = 500, num = 10)]
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]

In [4]:
# Define o número de folds do K-fold
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Define o modelo de classificação
model = RandomForestClassifier()

# Define o grid de parâmetros a ser testado
random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [5]:
# Define a técnica de Random Search para escolha dos melhores parâmetros
rf_random = RandomizedSearchCV(estimator = model, param_distributions = random_grid, n_iter = 100,
                               cv = kfold, verbose=2, random_state=42, n_jobs = -1)

# Treina o modelo
rf_random.fit(X_train, y_train)

# Realiza a predição com o modelo
y_pred = rf_random.predict(X_test)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


In [6]:
# Imprime a matriz de confusão
cf_matrix = confusion_matrix(y_test, y_pred)
print(cf_matrix)

[[32  0  0  0  1  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  1  0  0  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  0  1  0 39]]


#### 2. Após a etapa de treinamento, analise o modelo respondendo as questões a seguir:
- 2.1 Qual a acurácia do modelo? Justifique
- 2.2 O modelo teve uma boa performance? Justifique
- 2.3 Quais foram os melhores parâmetros escolhidos? Justifique
- 2.4 Quais as principais dificuldades encontradas para a criação do seu modelo de classificação?

In [ ]:
# Analisando o modelo
# a) Qual a acurácia do modelo? Justifique.
accuracy = rf_random.score(X_test, y_test)
print('Acurácia do modelo:', accuracy)
# A acurácia do modelo foi de 0.975, o que significa que ele acerta 97.5% das vezes nas predições. Isso demonstra 
# que o modelo possui uma boa capacidade de generalização.

# b) O modelo teve uma boa performance? Justifique.
Sim, o modelo teve uma boa performance. Como ele acertou 97.5% das vezes, isso indica que ele conseguiu estabelecer 
padrões na base de treinamento e aplicá-los de forma eficiente nos dados de teste. Além disso, a matriz de confusão 
revela que o modelo teve uma perfomance razoavelmente uniforme para todas as classes.

# c) Quais foram os melhores parâmetros escolhidos? Justifique.
O Random Search selecionou os seguintes parâmetros como sendo os melhores para este modelo:
{'n_estimators': 300,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_depth': 80,
 'bootstrap': False}
Através desses parâmetros, é possível balancear a complexidade do modelo com a sua capacidade de generalização, 
evitando overfitting ou underfitting.

# d) Quais as principais dificuldades encontradas para a criação do seu modelo de classificação?
As principais dificuldades encontradas para a criação do modelo de classificação foram relacionadas à escolha dos 
parâmetros a serem utilizados, principalmente em relação à complexidade do modelo e ao seu equilíbrio entre 
precisão e generalização. Além disso, foi necessário entender a estrutura da base de dados para aplicar as técnicas 
de separação em treinamento e teste, validação cruzada e matriz de confusão.


#### 3. Faça uma pesquisa para conhecer um pouco mais sobre o universo de Machine Learning e responda as questões a seguir:
- 3.1 Qual é a diferença entre um parâmetro de modelo e um algoritmo de aprendizagem de hiperparâmetro?
- 3.2 Você pode citar quatro dos principais desafios do aprendizado de máquina?
- 3.3 Se o seu modelo tem um ótimo desempenho nos dados de treinamento, mas generaliza mal para novas instâncias, o que está acontecendo? Você pode citar três soluções possíveis?
- 3.4 O que é um conjunto de teste e por que você  deveria usa-lo?
- 3.5 Qual é o propósito de um conjunto de validação?
- 3.6 O que pode dar errado se você ajustar hiperparâmetro usando o conjunto de teste?

#### Respostas:
3.1 Um parâmetro de modelo é uma configuração interna do modelo que é aprendida durante o treinamento, como os pesos em uma rede neural, enquanto um hiperparâmetro é uma configuração externa ao modelo, como a taxa de aprendizagem ou o número de camadas em uma rede neural.

3.2 Quatro dos principais desafios do aprendizado de máquina são: lidar com dados incompletos, lidar com dados desbalanceados, evitar o sobreajuste (overfitting) e escolher o algoritmo de aprendizado correto.

3.3 Se um modelo tem um ótimo desempenho nos dados de treinamento, mas generaliza mal para novas instâncias, isso significa que o modelo está sobreajustando os dados de treinamento e não consegue generalizar para novos dados. Algumas soluções possíveis são: aumentar a quantidade de dados de treinamento, reduzir a complexidade do modelo e usar regularização.

3.4 Um conjunto de teste é um conjunto de dados separado do conjunto de treinamento que é usado para avaliar o desempenho do modelo após o treinamento. É importante usar um conjunto de teste para avaliar se o modelo está generalizando bem para novos dados e evitar o sobreajuste aos dados de treinamento.

3.5 O propósito de um conjunto de validação é avaliar diferentes configurações de hiperparâmetros e escolher aquela que resulta no melhor desempenho no conjunto de validação. Isso é importante para evitar o ajuste excessivo aos dados de treinamento e garantir que o modelo generalize bem para novos dados.

3.6 Ajustar hiperparâmetros usando o conjunto de teste pode levar ao ajuste excessivo aos dados de teste e resultar em um modelo que não generaliza bem para novos dados. Isso é conhecido como vazamento de informações (leakage) e pode ser evitado usando um conjunto de validação separado para ajustar os hiperparâmetros.